urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AAapp.views.home', name='home'),
    # url(r'^AAapp/', include('AAapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'AAapp.AA.views.welcome'),
    url(r'^accounts/login/$', 'AAapp.AA.views.welcome'),
    url(r'^new_expense/$', 'AAapp.AA.views.new_expense'),
    url(r'^view_expense/(\d+)/', 'AAapp.AA.views.view_expense'),
    url(r'^logout/$', 'AAapp.AA.views.signoff'),
    url(r'^new_account/$', 'AAapp.AA.views.new_account'),
)

AA/forms.py
from django import forms
from django.contrib.auth.models import User
from AA.models import Expense

class NameModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.get_full_name()
        
class NewExpenseForm(forms.Form):
    money = forms.FloatField(required=True)
    title = forms.CharField(required=True, max_length=100)
    participants = NameModelMultipleChoiceField(required=True, queryset=User.objects.all(),
            widget=forms.CheckboxSelectMultiple)

class NewAccountForm(forms.Form):
    username = forms.CharField(required=True, max_length=100)
    password = forms.CharField(required=True, max_length=100, widget=forms.PasswordInput)
    email = forms.EmailField(required=True, max_length=100)
    first_name = forms.CharField(required=True, max_length=100)
    last_name = forms.CharField(required=True, max_length=100)

class LoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=100)
    password = forms.CharField(required=True, max_length=100, widget=forms.PasswordInput)

templates/admin.html
{% extends 'base.html' %}

{% block title %}
Welcome {{ user.username }}
{% endblock %}


{% block content %}

<ul>
    {% if user.is_superuser %}
    <li><a href="/new_expense">新消费</a></li>
    <li><a href="/new_account">新账户</a></li>
    {% endif %}
    <li><a href="/logout">登出</a></li>
</ul>
<div class="column">
    {% if user.is_superuser %}
        <h1>账户明细</h1>
        <table border="1px" cellpadding="5px">
            <tr>
                <td>账户</td>
                <td>余额</td>
            </tr>
            {% for user in allusers %}
            <tr>
                <td>{{ user.get_full_name }}</td>
                <td>{{ user.accountinfo.balence }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td>总计</td>
                <td>{{ total }}</td>
            </tr>
        </table>

        <div id="detail">
        </div>
    {% else %}
        <p>Permission Denied</p>
    {% endif %}
</div>
{% endblock %}

templates/balences.html
{% extends 'base.html' %}

{% block title %}
Welcome {{ user.username }}
{% endblock %}


{% block content %}

<ul>
    {% if user.is_superuser %}
    <li><a href="/new_expense">新消费</a></li>
    <li><a href="/new_account">新账户</a></li>
    {% endif %}
    <li><a href="/logout">登出</a></li>
    <li><a href="/">返回</a></li>
</ul>
<div class="column">
    {% if user.is_superuser %}
            
    {% else %}
        <h1>你参与的消费</h1>
        {% if user.expense_set.all %}
            <ul>
                {% for expense in user.expense_set.all %}
                <a href="/view_expense/{{ expense.id }}/">
                    <li><div>
                        <p>{{ expense.title }}<span>({{ expense.each }})</p>
                        <span>at {{ expense.pub_datetime }}</span>
                    </div></li>
                </a>
                {% endfor %}
            </ul>
        {% else %}
            <p>没有任何你参与的消费</p>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

templates/base.html
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div id="head">
            <h1> 欢迎使用 Renren AA app </h1>
            {% if user.is_authenticated %}
            <p> {{ user.get_full_name }}, 你上次登录时间是 {{ user.last_login }}, 余额： {{ user.accountinfo.balence }} </p>
            {% endif %}
        </div>
        <div id="content">
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

templates/error.html
{% extends 'base.html' %}

{% block title %}
Welcome {{ user.username }}
{% endblock %}


{% block content %}
<ul>
    <li><a href="/">返回</a></li>
</ul>
<h1>错误</h1>
<p>{{ error }}</p> 
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
Welcome {{ user.username }}
{% endblock %}


{% block content %}

<ul>
    <li><a href="/logout">登出</a></li>
</ul>
<div class="column">
    <h1>你参与的消费</h1>
    {% if user.expense_set.all %}
        <ul>
            {% for expense in user.expense_set.all %}
            <a href="/view_expense/{{ expense.id }}/">
                <li><div>
                    <p>{{ expense.title }}<span>({{ expense.each }})</p>
                    <span>at {{ expense.pub_datetime }}</span>
                </div></li>
            </a>
            {% endfor %}
        </ul>
    {% else %}
        <p>没有任何你参与的消费</p>
    {% endif %}
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}登录{% endblock %}

{% block content %}
<h1>登录</h1>
<div>
    <form action="." method="post">
        {{ form.as_p }}
        <input type="submit" value="Login" />
    </form>
</div>
{% endblock %}

templates/new_account.html
{% extends 'base.html' %}

{% block title %}
新账户
{% endblock %}


{% block content %}

<ul>
    <li><a href="/">返回</a></li>
</ul>
<div class="column">
    <form action="." method="POST">
        {{ form.as_p }}
        <input type="SUBMIT" value="Go!" />
    </form>
</div>
{% endblock %}

templates/new_expense.html
{% extends 'base.html' %}

{% block title %}
新建消费
{% endblock %}

{% block content %}
<ul>
    <li><a href="/">返回</a></li>
</ul>
<h1>新建消费</h1>
<div>
    <form id="frm" action="." method="post">
        {{ form.as_p }}
        <input type="submit" value="Go!" onClick="sure()" />
    </form>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script type="text/javascript">
    function sure() {
        var count = $(':checked').length;
        var total = $('#id_money').val();
        var each = parseInt(total)/count;
        var message = "总额:" + total + ", 人均：" + each + ". 确认创建?";
        if(confirm(message)) {
            frm.submit(); 
        }
    }
</script>
{% endblock %}

templates/view_expense.html
{% extends 'base.html' %}

{% block title %}
查看消费记录
{% endblock %}

{% block content %}
<ul>
    <li><a href="/">返回</a></li>
</ul>
<h1>查看消费</h1>
<div>
    <h2>{{ expense.title }}</h2>
    <p>{{ expense.pub_datetime }}</p>
    <p>人均：{{ expense.each }}</p>
    <p>总额：{{ expense.money }}</p>
    <p>参与者</p>
    <ul>
        {% for participant in expense.participants.all %}
            <li> {{ participant.get_full_name }} </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}